/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:b8319142-504e-4408-8a13-ecc686a9b10b",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_EL62McmbB",
    "aws_user_pools_web_client_id": "1qcvmqnjrh3lkmdle57rse6qbu",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://abolj4xujjgbncwxfnb35tdgoq.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
